# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alphapi - The Human-Readable Base-16 System
email: paul@alphapi.dev
description: >- # this means to ignore newlines until "baseurl:"
  Alphapi is an innovative base-16 numbering system that replaces traditional hexadecimal digits with the letters 'a' to 'p', 
  providing a more human-readable, compact representation for large numbers and symbolic identifiers. 
  This open-source project aims to develop and promote Alphapi, offering documentation, conversion tools, coding libraries, and a community platform for users and contributors.
  Perfect for developers, data scientists, and researchers looking to enhance data representation in their projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.alphapi.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: alphapid
github_username:  alphapi-dev

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
